# This is a basic workflow to help you get started with Actions

name: PYTests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tests:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        
      # Pytest builds app before running it so we need the sdk to build it
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.9.0
      
      - name: Install pip
        run: pip install --upgrade pip
        
      - name: Pip install pytest
        run: pip install pytest
        
      - name: Pip install requests
        run: pip install requests
        
      - name: Run tests with pytest
        run: pytest tests/
